version: '2'
services:
  blog:
    container_name: hexo-blog
    build: .
    image: hexo-blog
    volumes:
      - nginx:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=106.14.140.93
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=106.14.140.93
      - LETSENCRYPT_EMAIL=1071956678@qq.com
    networks: 
      - proxy
volumes:
  nginx:

networks:
  proxy:
    external: true